services:
  downloader:
    build:
      context: ./services/downloader
    container_name: downloader
    restart: unless-stopped
    volumes:
      - /data:/data
    ports:
      - "8081:8080"
    env_file:
      - .env